# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f95769889a2aee52b3042b0ad3c828086679d8c9b221a1af8a98a96e96ad930c7794e12e7db6c0da7ada67305c4c37a7e3476289e4561054f10db7660bed934e

test:
  secret_key_base: eeb6a1e0e3c1d739e4075e29432a70e2e7f3bb1f552d56979c70d55d432844f5e11e0aa3b3c359acc5db9b88a61f22022a2a946c7be7fff9da1bd39b6b7bf3b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
